# Generated by Django 3.2.3 on 2021-06-02 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=200)),
                ('cust_id', models.EmailField(max_length=200)),
                ('curr_balance', models.IntegerField()),
            ],
        ),
    ]
