# Generated by Django 3.2.3 on 2021-06-05 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210602_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='id',
        ),
        migrations.AlterField(
            model_name='customers',
            name='cust_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
