# Generated by Django 3.2.3 on 2021-06-05 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210605_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfers',
            name='receiver_id',
            field=models.ForeignKey(default=1000, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_set', to='main.customers'),
        ),
        migrations.AlterField(
            model_name='transfers',
            name='sender_id',
            field=models.ForeignKey(default=1000, on_delete=django.db.models.deletion.CASCADE, related_name='sender_set', to='main.customers'),
        ),
    ]
